import Head from 'next/head'
import Image from 'next/image'
import Border from '../components/Border'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Walmart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {/* navbar */}
      <Navbar />
      {/* Hero */}
      <Hero />
      {/* Border */}
      <Border />
      {/* Footer */}
      <Footer />
    </div>
  )
}
